[package]
name = "cairo-fuzzer"
version = "0.1.1"
edition = "2021"
description = "A library for fuzzing cairo and starknet contracts"
readme = "README.md"
license = "AGPL-3.0"
license-file = "LICENSE"
repository = "https://github.com/FuzzingLabs/cairo-fuzzer"

[dependencies]
cairo-rs = { version = "0.1.0", git="https://github.com/FuzzingLabs/cairo-rs/", rev="d938ffb4a36e3e266bb51955d4a76cdae38e44c2"}
chrono = "0.4.19"
rand = "0.8.5"
num-bigint = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
serde = "*"
clap = { version = " 4.0.29", features = ["derive"] }
log = "*"
thiserror = "1.0.32"
cairo-rs-py = {version = "0.1.0", git = "https://github.com/FuzzingLabs/cairo-rs-py", rev="c168a767ea41fd04570c3d33874c0f442fca092d"}
pyo3 = { version = "0.16.5" }
regex = "*"
curl = "*"

[features]
extension = ["pyo3/num-bigint", "pyo3/extension-module"]
default = ["pyo3/num-bigint", "pyo3/auto-initialize"]
