[package]
name = "cairo-fuzzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-vm = { git="https://github.com/FuzzingLabs/cairo-rs/", rev="9c9435062c96e8052eacd3e58e5d37e904fee1c4"}
cairo-felt = { git="https://github.com/FuzzingLabs/cairo-rs/", rev="9c9435062c96e8052eacd3e58e5d37e904fee1c4"}

chrono = "0.4.19"
rand = "0.8.5"
num-bigint = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
serde = "*"
clap = { version = " 4.0.29", features = ["derive"] }
log = "*"
thiserror = "1.0.32"