[package]
name = "test-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.209"
serde_json = "1.0.127"
sierra-analyzer-lib = { path = "./sierra-analyzer/lib" }
