[package]
name = "scripts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-fuzzer = {path = "../"}

[[bin]]
name = "starknet-fuzzer"
path = "./src/starknet_fuzz.rs"